#!/usr/bin/env ruby
# frozen_string_literal: true

# Script to generate Homebrew formula for Tingly-Box
# Usage: ruby Formula/generate.rb VERSION=<version> [SHA256_XXX=<hash>]

require 'fileutils'

VERSION = ENV['VERSION'] || (raise "VERSION environment variable is required. Usage: VERSION=<version> ruby Formula/generate.rb")
# Script is at Formula/generate.rb, formula goes in same directory
FORMULA_DIR = __dir__
FORMULA_FILE = File.join(FORMULA_DIR, 'tingly-box.rb')

# Get SHA256 hashes from environment or placeholders
SHA256 = {
  darwin_arm64: ENV['SHA256_DARWIN_ARM64'] || '',
  darwin_amd64: ENV['SHA256_DARWIN_AMD64'] || '',
  linux_amd64: ENV['SHA256_LINUX_AMD64'] || ''
}.freeze

def generate_formula
  <<~RUBY
    # DO NOT EDIT MANUALLY
    # This file is generated by: task brew:generate
    # To regenerate, run: task brew:generate VERSION=<version>

    class TinglyBox < Formula
      desc "Local AI intelligence layer - autonomous AI model proxy and orchestrator"
      homepage "https://github.com/tingly-dev/tingly-box"

      # depends_on "unzip" => :build

      on_macos do
        on_arm do
          url "https://github.com/tingly-dev/tingly-box/releases/download/#{VERSION}/tingly-box-macos-arm64.zip"
          sha256 "#{SHA256[:darwin_arm64]}"
        end

        on_intel do
          url "https://github.com/tingly-dev/tingly-box/releases/download/#{VERSION}/tingly-box-macos-amd64.zip"
          sha256 "#{SHA256[:darwin_amd64]}"
        end
      end

      on_linux do
        on_intel do
          url "https://github.com/tingly-dev/tingly-box/releases/download/#{VERSION}/tingly-box-linux-amd64.zip"
          sha256 "#{SHA256[:linux_amd64]}"
        end
      end

      def install
        # Zip extracts to platform-specific binary names, install with standard name
        if OS.mac?
          if Hardware::CPU.arm?
            bin.install "tingly-box-macos-arm64" => "tingly-box"
          else
            bin.install "tingly-box-macos-amd64" => "tingly-box"
          end
        else
          bin.install "tingly-box-linux-amd64" => "tingly-box"
        end
      end

      test do
        version_output = shell_output("\#{bin}/tingly-box version 2>&1", 1)
        assert_match /\d+/, version_output, "Expected version output to contain version number"
      end
    end
  RUBY
end

def main
  FileUtils.mkdir_p(FORMULA_DIR)

  File.write(FORMULA_FILE, generate_formula)

  puts "Formula generated: #{FORMULA_FILE}"
  puts "Version: #{VERSION}"
  puts ''
  puts 'Next steps:'
  puts '  1. Commit formula to Formula/ directory'
  puts '  2. Push to trigger update-formula.yml workflow'
  puts '  3. Merge the PR when ready'
end

main if __FILE__ == $PROGRAM_NAME
