# DO NOT EDIT MANUALLY
# This file is generated by: task brew:generate
# To regenerate, run: task brew:generate VERSION=<version>

class TinglyBox < Formula
  desc "Local AI intelligence layer - autonomous AI model proxy and orchestrator"
  homepage "https://github.com/tingly-dev/tingly-box"
  version "v0.260415.1045-hotfix"

  # depends_on "unzip" => :build

  on_macos do
    on_arm do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v0.260415.1045-hotfix/tingly-box-macos-arm64.zip"
      sha256 "30fe26f81d7b10ec6c37d984aad6d20daa9a544d5d9ab613057080d4dcdf19c4"
    end

    on_intel do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v0.260415.1045-hotfix/tingly-box-macos-amd64.zip"
      sha256 "71328f27c9e43cd57bdf076373fd297076095826aaa6d95d96b26f55b54889d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v0.260415.1045-hotfix/tingly-box-linux-amd64.zip"
      sha256 "4dca7e5eb65136a7c0ffbf672e09bb91246d5e07e3884ff87212e1caa01cecf8"
    end

    on_arm do
      url "https://github.com/tingly-dev/tingly-box/releases/download/v0.260415.1045-hotfix/tingly-box-linux-arm64.zip"
      sha256 "38e245fffd8a29dcbb511b0f88e6de318e1afcfd3461266ea9d1492f8d83a9ce"
    end
  end

  def install
    # Zip extracts to platform-specific binary names, install with standard name
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "tingly-box-macos-arm64" => "tingly-box"
      else
        bin.install "tingly-box-macos-amd64" => "tingly-box"
      end
    else
      # Linux
      if Hardware::CPU.arm?
        bin.install "tingly-box-linux-arm64" => "tingly-box"
      else
        bin.install "tingly-box-linux-amd64" => "tingly-box"
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/tingly-box version 2>&1", 1)
    assert_match /\d+/, version_output, "Expected version output to contain version number"
  end
end
